global:
  scrape_interval:     10s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'signifier'
    scrape_interval: 1s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
