#!/usr/bin/env python3

#  __________                         __  .__                              .__     
#  \______   \_____    ______ _______/  |_|  |_________  ____  __ __  ____ |  |__  
#   |     ___/\__  \  /  ___//  ___/\   __\  |  \_  __ \/  _ \|  |  \/ ___\|  |  \ 
#   |    |     / __ \_\___ \ \___ \  |  | |   Y  \  | \(  <_> )  |  / /_/  >   Y  \
#   |____|    (____  /____  >____  > |__| |___|  /__|   \____/|____/\___  /|___|  /
#                  \/     \/     \/            \/                  /_____/      \/ 

"""Signify module to pass audio generated by the Clip Manager to the designated
audio output device. This module also produces analyise data on the incoming audio
stream, which can be sent to the arduino to modulate the LEDs."""

# Primary research sources:
# - https://stackoverflow.com/questions/66964597/python-gui-freezing-problem-of-thread-using-tkinter-and-sounddevice


from multiprocessing import Event
import time
import queue
import random
import logging
import threading
import numpy as np
import sounddevice as sd


RHISTORY = 2
DEFAULT_CONF = {
    "enabled":True,
    "loopback_return":1,
    "hw_loop_output":0,
    "sample_rate":44100,
    "buffer":2048 }

sd.default.device = (2,0)
sd.default.samplerate = 44100
sd.default.channels = 1
y_roll = np.random.rand(RHISTORY, DEFAULT_CONF['buffer']) / 1e16

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
q = queue.Queue()
q.maxsize = 10


class Stream(threading.Thread):
    """A PulseAudio loopback stream to analyse the audio\
    and output to the hardware device.\n
    Supply the audio portion of `config.json`, i.e. `config['audio']`."""
    def __init__(self, config=None):
        super().__init__()
        logging.debug(f'Streaming module detected the following devices:\n{sd.query_devices()}')
        if config is None:
            config = DEFAULT_CONF
        else:
            self.active = True
            self.input = config['loopback_return']
            self.output = config['hw_loop_output']
            self.sample_rate = config['sample_rate']
            self.buffer = config['buffer']
        self.y_roll = np.random.rand(RHISTORY, self.buffer) / 1e16
        self.amplitude = 0
        self.event: threading.Event
        self.stream: Stream
        self.streaming = True
        self.prev_amp = 0
        self.time = 0
        sd.default.channels = 1
        sd.default.device = (self.input, self.output)
        sd.default.samplerate = self.sample_rate
        logger.debug('Audio passthrough module ready.')


    def run(self):
        """Threaded routine that starts a PortAudio stream for piping Signifier\
        audio to the hardware audio output.\n
        Also executes audio analysis during the callback and updates audio\
        descriptors available from `get_descriptors()` function."""
        self.event = threading.Event()
        with sd.Stream(device=(self.input, self.output),
                   samplerate=self.sample_rate, channels=1,
                   callback=self.callback) as self.stream:
            while self.streaming:
                self.time = time.time()
                try:
                    self.amplitude = q.get(timeout=1)
                except queue.Empty:
                    pass
                if not self.event.is_set():
                    sd.sleep(1)
                else:
                    self.streaming = False
            #self.event.wait()
            try:
                sd.Stream.abort(self)
                print("ABORTED STREAM!")
            except AttributeError:
                sd.CallbackAbort()
                print("ABORTED CALLBACK!")
                self.streaming = False


    def terminate(self):
        """Requests that the Stream thread aborts current buffer processing\
        and provides an `event.set()` call to terminate the thread."""
        print()
        logger.info(f'Stopping audio streaming thread...')
        self.streaming = False
        self.event.set()
        sd.sleep(10)
        self.stream.abort()


    def callback(self, indata, outdata, frames, time, status):
        """The primary function called by the Streaming thread. This function\
        calculates the amplitude of the input signal, then streams it to the\
        output audio device."""
        if self.streaming:
            cat = np.concatenate(indata)
            if status:
                print(status)
            self.y_roll[:-1] = self.y_roll[1:]
            self.y_roll[-1, :] = np.copy(indata[0])
            y_data = np.concatenate(self.y_roll, axis=0).astype(np.float32)
            amp = np.max(np.abs(y_data))
            try:
                q.put_nowait(amp)
            except queue.Full:
                pass
            outdata[:] = indata


    def get_descriptors(self) -> dict:
        """Return a dictionary with audio analysis values returned from thread."""
        try:
            new_amp = q.get_nowait()
        except queue.Empty:
            return {"amplitude":self.amplitude}
        if self.amplitude != new_amp:
            self.amplitude = new_amp
            print(self.amplitude)
        return {"amplitude":self.amplitude}
